const currencies: string[] = [
    "United States Dollar",
    "Euro",
    "Japanese Yen",
    "British Pound Sterling",
    "Swiss Franc",
    "Canadian Dollar",
    "Australian Dollar",
    "Chinese Yuan",
    "Indian Rupee",
    "Brazilian Real",
    "Mexican Peso",
    "South African Rand",
    "Russian Ruble",
    "Swedish Krona",
    "New Zealand Dollar",
    "Singapore Dollar",
    "Hong Kong Dollar",
    "Norwegian Krone",
    "South Korean Won",
    "Turkish Lira",
    "United Arab Emirates Dirham",
    "Saudi Riyal",
    "Danish Krone",
    "Polish Złoty",
    "Thai Baht",
    "Indonesian Rupiah",
    "Czech Koruna",
    "Malaysian Ringgit",
    "Hungarian Forint",
    "Israeli New Shekel",
    "Philippine Peso",
    "Argentine Peso",
    "Egyptian Pound",
    "Chilean Peso",
    "Colombian Peso",
    "Pakistani Rupee",
    "Nigerian Naira",
    "Kenyan Shilling",
    "Kuwaiti Dinar",
    "Qatari Riyal",
    "Moroccan Dirham",
    "Icelandic Króna",
    "Croatian Kuna",
    "Vietnamese Dong",
    "Ukrainian Hryvnia"
  ];

  export default currencies